image: djcash/ci_php_base_system:v1

develop_deploy:
  script:
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; set net:timeout 5; set net:max-retries 3; set net:reconnect-interval-multiplier 1; set net:reconnect-interval-base 5; mirror -X .git/* -X .gitlab-ci.yml --reverse --verbose --delete --no-perms ./ /aikan/pay.aikoversea.com/; bye"
  only :
    - master